import 'dart:io';

import 'package:closetmixer/widgets/custom_drop_down.dart';
import 'package:flutter/material.dart';
import 'package:closetmixer/core/app_export.dart';
import 'package:image_picker/image_picker.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

//import '/../core/services/image_color_service.dart'; // Correct the import path

// void main() {
//   runApp(const FigmaToCodeApp());
// }

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  //String imageUrl = '';
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          OutfitAdd(),
        ]),
      ),
    );
  }
}

class OutfitAdd extends StatelessWidget {
  final ImagePicker _picker = ImagePicker();

  String imageUrl = '';

  Future<void> _openCamera(BuildContext context) async {
    final XFile? photo = await _picker.pickImage(source: ImageSource.camera);

    if (photo != null) {
      // Use the photo file. For example:
      print('Photo path: ${photo.path}');

      String uniqueFileName = DateTime.now().millisecondsSinceEpoch.toString();

      Reference referenceRoot = FirebaseStorage.instance.ref();
      Reference referenceDirImages = referenceRoot.child('images');

      Reference referenceImageToUpload =
          referenceDirImages.child(uniqueFileName);

      try {
        await referenceImageToUpload.putFile(File(photo!.path));

        imageUrl = await referenceImageToUpload.getDownloadURL();
      } catch (error) {}
    }
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 375,
          height: 812,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Color(0xFFD9D9D9),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(25),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 27,
                top: 70,
                child: Container(
                  width: 323,
                  height: 24,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 23.71,
                          height: 24,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(children: []),
                        ),
                      ),
                      Positioned(
                        left: 299.29,
                        top: 0,
                        child: Container(
                          width: 23.71,
                          height: 24,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(children: []),
                        ),
                      ),
                      Positioned(
                        left: 251.88,
                        top: 0,
                        child: Container(
                          width: 23.71,
                          height: 24,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(children: []),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 280,
                top: 107,
                child: Container(
                  width: 60,
                  height: 171,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 294,
                top: 113,
                child: SizedBox(
                  width: 34,
                  height: 19,
                  child: Text(
                    'colors',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 10,
                      fontFamily: 'Public Sans',
                      fontWeight: FontWeight.w700,
                      height: 0.24,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 296,
                top: 142,
                child: Container(
                  width: 29,
                  height: 29,
                  decoration: ShapeDecoration(
                    color: Color(0xFF979797),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 296,
                top: 181,
                child: Container(
                  width: 28,
                  height: 28,
                  decoration: ShapeDecoration(
                    color: Color(0xFF979797),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: -5,
                top: 12,
                child: Container(
                  width: 375,
                  height: 44,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 293.67,
                        top: 17.33,
                        child: Container(
                          width: 66.66,
                          height: 11.34,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 42.33,
                                top: 0,
                                child: Container(
                                  width: 24.33,
                                  height: 11.33,
                                  child: Stack(children: []),
                                ),
                              ),
                              Positioned(
                                left: 22.03,
                                top: 0,
                                child: Container(
                                  width: 15.27,
                                  height: 10.97,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                          "https://via.placeholder.com/15x11"),
                                      fit: BoxFit.fill,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0.34,
                                child: Container(
                                  width: 17,
                                  height: 10.67,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                          "https://via.placeholder.com/17x11"),
                                      fit: BoxFit.fill,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 20,
                        top: 12,
                        child: Container(
                          width: 54,
                          height: 21,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(32),
                            ),
                          ),
                          child: Stack(children: []),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 593,
                child: Container(
                  width: 302,
                  height: 169,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 302,
                          height: 169,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(20),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 41,
                        top: 46,
                        child: SizedBox(
                          width: 245,
                          height: 23,
                          child: Text(
                            'add comma separated tags',
                            style: TextStyle(
                              color:
                                  Colors.black.withOpacity(0.49000000953674316),
                              fontSize: 12,
                              fontFamily: 'Public Sans',
                              fontWeight: FontWeight.w500,
                              height: 0.17,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 146,
                        top: 109,
                        child: SizedBox(
                          width: 124,
                          height: 25,
                          child: Text(
                            'Add to outfit',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 13,
                              fontFamily: 'Public Sans',
                              fontWeight: FontWeight.w700,
                              height: 0.14,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 27,
                        top: 93,
                        child: Container(
                          width: 166,
                          height: 41,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 166,
                                  height: 41,
                                  decoration: BoxDecoration(
                                    gradient: LinearGradient(
                                      begin: Alignment(1.00, 0.00),
                                      end: Alignment(-1, 0),
                                      colors: [
                                        Color(0xFFDEAAFF),
                                        Color(0xFF301E3C)
                                      ],
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 9,
                                top: 8,
                                child: SizedBox(
                                  width: 147,
                                  height: 26,
                                  child: Text(
                                    'Enter category',
                                    style: TextStyle(
                                      color: Colors.white,
                                      fontSize: 20,
                                      fontFamily: 'Public Sans',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 236,
                        top: 99,
                        child: Container(
                          width: 34,
                          height: 32,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                        ),
                      ),
                      Positioned(
                        left: 19,
                        top: 18,
                        child: SizedBox(
                          width: 267,
                          height: 28,
                          child: Text(
                            'Enter Outfit Name',
                            style: TextStyle(
                              color:
                                  Colors.black.withOpacity(0.44999998807907104),
                              fontSize: 17,
                              fontFamily: 'Public Sans',
                              fontWeight: FontWeight.w700,
                              height: 0.08,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 50,
                top: 351,
                child: Container(
                  width: 273,
                  height: 61,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 273,
                          height: 61,
                          decoration: ShapeDecoration(
                            color: Color(0xFF06070D),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 96.18,
                        top: 23.29,
                        child: SizedBox(
                          width: 87.44,
                          height: 15.53,
                          child: Text.rich(
                            TextSpan(children: []),
                            textAlign: TextAlign.center,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 144,
                top: 365,
                child: ElevatedButton(
                  style: ElevatedButton.styleFrom(
                    shadowColor: Colors.transparent, // Remove shadow
                    elevation: 0,
                  ),
                  onPressed: () => _openCamera(context),
                  child: Text(
                    'Add Photo',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 18,
                      fontFamily: 'Public Sans',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 296,
                top: 219,
                child: Container(
                  width: 28,
                  height: 28,
                  decoration: ShapeDecoration(
                    color: Color(0xFF979797),
                    shape: OvalBorder(),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
